---
title: 'analysis of Pterostichus madidus morphology on 2004-2005 ground beetle data'
author: ""
date:
output:
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
    code_download: TRUE
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r packages}
library(tidyverse)
library(sf)
library(terra)
library(units)

library(here)

options(mc.cores = 4) 
```

# Introduction

# Data loading and preparation

First we load all the data (note that *P. madidus* data come in two separate files, one for the red-legged morph, one for the black-legged).

```{r data}
raw_sites <-read_sf(here("data","GIS_layers","rennes2004_sites_centroids.gpkg"),layer="rennes2004_sites_centroids")

IMD <- rast(here("data","GIS_layers","IMD_2006_020m_eu_03035_d03_E30N20.tif"))
names(IMD)<-"IMD"

NAflag(IMD) <- 255 # IMPORTANT: GHSL spec: 255 = nodata
```


make buffers

```{r}
buffer_widths <- c(100,300,600,900,1200,1500,1800)

for (i in 1:length(buffer_widths)){
  
buffers <-st_buffer(raw_sites,dist=set_units(buffer_widths[i],"m"))

write_sf(buffers,
         here("data","GIS_layers",paste0("rennes2004_buffers_",buffer_widths[i],"m.gpkg")),
         layer=paste0("rennes2004_buffers_",buffer_widths[i],"m")
)
}

```



```{r}
urban_info <- tibble(SITE=raw_sites$site)

for (i in 1:length(buffer_widths)){

buffers<-read_sf(here("data","GIS_layers",paste0("rennes2004_buffers_",buffer_widths[i],"m.gpkg")),
         layer=paste0("rennes2004_buffers_",buffer_widths[i],"m"))
reproj_vector=project(vect(buffers),IMD)

urban_info[,paste0("meanIMD_",buffer_widths[i],"m")] <-  terra::extract(x=IMD,
  y=reproj_vector,fun="mean",na.rm=TRUE  )$IMD
}

write_csv(urban_info,
          here("data","processed_data","urban_info_IMD.csv"))

```




